### PR TITLE
fix broken links, add disclaimer for pools (already deployed), fix builds

### LINKED ISSUE #102: Links in header broken again
**cannot use external links**

### PR DESCRIPTION
**Pull request by vepkenez**
Fixes #102

### CODE REVIEW

File: packages/react-app/src/components/header.js [hunk 1]
```diff
@@ -61,9 +61,9 @@ export default function (props) {
                 <Navbar.Collapse id="basic-navbar-nav">
                     <Nav className="d-flex justify-content-end align-items-center">
 
-                        <Nav.Link href="/new/worker">New Stake</Nav.Link>
-                        <Nav.Link href="/manage">Manage</Nav.Link>
-                        <Nav.Link href="https://www.coinbase.com/earn/nucypher" target="blank">Learn</Nav.Link>
+                        <Nav.Link><Link to="/new/worker">New Stake</Link></Nav.Link>
+                        <Nav.Link><Link to="/manage">Manage</Link></Nav.Link>
+                        <Nav.Link><Link to="https://www.coinbase.com/earn/nucypher" target="blank"></Link>Learn</Nav.Link>
```
Comment (derekpierre) [inline packages/react-app/src/components/header.js]: I thought `<Link>` doesn't work with external links...which is why is why it was `<a>` before?

Comment (vepkenez) [reply packages/react-app/src/components/header.js]: That wasn't the issue.  The issue is that the site is a single page app with its own router. https://reactrouter.com/web/guides/quick-start
All internal links from one page to another need to use the router which is the 
`<Link to="location">`
  
Now that I look at this, it looks like I messed up the _external_ link 🤦

Comment (vepkenez) [reply packages/react-app/src/components/header.js]: I'm working on fixing the issue with why it crashes on external entry like if you just go directly to here:
https://stake.nucypher.network/new/worker/join

Comment (derekpierre) [reply packages/react-app/src/components/header.js]: So just to confirm, if you click on 'Learn' the external link works correctly?

Comment (vepkenez) [reply packages/react-app/src/components/header.js]: Yep I reverted that one.
And now with the build being fixed,  the internal ones _would_ work but it's still better to use router links for those since it will reload the whole page if you use an href="" link (this may depend on different browsers)

**Review by derekpierre — APPROVED** [review]
🎸

File: package.json [hunk 2]
```diff
@@ -13,7 +13,8 @@
     "subgraph:codegen": "yarn workspace @project/subgraph codegen",
     "subgraph:build": "yarn workspace @project/subgraph build",
     "subgraph:deploy": "yarn workspace @project/subgraph deploy",
-    "react-app:build": "yarn workspace @project/react-app build",
+    "react-app:build-production": "PUBLIC_URL=https://stake.nucypher.network yarn workspace @project/react-app build",
```
Comment (vepkenez) [inline package.json:16]: see this for explanation.
https://stackoverflow.com/questions/54340240/create-react-app-build-uncaught-syntaxerror-unexpected-token

With relative imports, anyone trying to directly load eg. https://stake.nucypher.network/new/worker/join,
statics would attempt to load from `https://stake.nucypher.network/new/worker/join/statics/js/something.js`
setting PUBLIC_URL forces the build to specify statics from absolute path.
